export const fakeUser = {
  id: 0,
  name: "Username",
  email: "example@mail.com",
  country: "Ukraine",
  city: "Kiev",
  crew: "Crew name",
  link: "https://some-link.com",
  type: "artist",
  active: true,
  created_at: "2020-09-26T15:40:59.000000Z",
  updated_at: "2020-09-26T15:40:59.000000Z",
};

// https://source.unsplash.com/collection/{COLLECTION ID}

export const fakeUserSpots = [
  {
    img: "https://source.unsplash.com/collection/1020791",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/9454911",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/9568384",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/9717149",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/9248817",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/9042806",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/9042799",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/1131562",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/778914",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/209138",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/1758353",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/566331",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2020,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/1856142",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2019,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/8469893",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2018,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/1199299",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2018,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/446755",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2017,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/1198107",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2017,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/8775791",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2017,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/762960",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2017,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/433313",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2017,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
  {
    img: "https://source.unsplash.com/collection/219941",
    artist: "Username",
    crew: "Crew name",
    status: "Live",
    year: 2016,
    linkToWork: "https://link-to-work.com",
    linkToVideo: "",
    category: "Walls",
    description: "",
  },
];
